# Auto theme flavour by time
run-shell ' \
  HOUR=$(date +%H); \
  if [ $HOUR -ge 7 ] && [ $HOUR -lt 18 ]; then \
    tmux set -g @catppuccin_flavour "latte"; \
  else \
    tmux set -g @catppuccin_flavour "frappe"; \
  fi \
'
set -g @catppuccin_pane_format "#( ~/.config/tmux/scripts/icons.sh #{pane_pid} ) #{pane_index}"
set -g @catppuccin_status_modules_right "pane current_session"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# https://that.guru/blog/automatically-set-tmux-window-name/
#set -g allow-rename on

#set-option -g status 2

#set -g status-position bottom
#set -g status-justify left
#set -g status-style 'fg=red'

# Determine icons based on the running process
#set -g @window_icons '#(  ~/.config/tmux/scripts/icons.sh #{pane_pid} )'
#set -g @pane_icons '#( ~/.config/tmux/scripts/icons.sh #{pane_pid} )'

set -g window-status-format " #[fg=#{@catppuccin_surface2}]#( ~/.config/tmux/scripts/icons.sh #{pane_pid} ) #I "
set -g window-status-current-format " #[fg=#{@catppuccin_blue},bold]#( ~/.config/tmux/scripts/icons.sh #{pane_pid} ) #I "

set -g pane

set -g status-right "#[fg=#{@catppuccin_blue}]#( ~/.config/tmux/scripts/icons.sh #{pane_pid} ) #[fg=#{@catppuccin_text}]#{pane_index} "



