set -g @extrakto_split_direction 'p'    # popup
set -g @extrakto_popup_size '70%'       # a bit larger
set -g @extrakto_copy_key 'enter'       # use default behavior
set -g @extrakto_insert_key 'tab'
set -g @extrakto_fzf_unset_default_opts 'false'

run-shell ~/.config/tmux/plugins/extrakto/extrakto.tmux

